// Generated by CoffeeScript 1.7.1
(function() {
  var FrTrie, empty, normalization_pattern, spaces;

  normalization_pattern = new RegExp('[^a-zA-Z ]', 'g');

  spaces = new RegExp(' ', 'g');

  empty = [];

  FrTrie = (function() {
    function FrTrie() {
      this.root = {};
      this.map = {};
    }

    FrTrie.prototype.add = function(id, text) {
      var i, w, word, words, _i, _j, _len, _ref, _ref1;
      this.map[id] = text;
      words = FrTrie.normalize(text).split(' ');
      for (i = _i = 0, _ref = words.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        word = "";
        _ref1 = words.slice(i);
        for (_j = 0, _len = _ref1.length; _j < _len; _j++) {
          w = _ref1[_j];
          word += w;
        }
        this.index(id, word);
      }
    };

    FrTrie.prototype.remove = function(id) {
      var i, text, w, word, words, _i, _j, _len, _ref, _ref1;
      if (!this.map[id]) {
        return;
      }
      text = this.map[id];
      delete this.map[id];
      words = FrTrie.normalize(text).split(' ');
      for (i = _i = 0, _ref = words.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        word = "";
        _ref1 = words.slice(i);
        for (_j = 0, _len = _ref1.length; _j < _len; _j++) {
          w = _ref1[_j];
          word += w;
        }
        this["delete"](id, word);
      }
    };

    FrTrie.prototype.update = function(id, text) {
      this.remove(id);
      this.add(id, text);
    };

    FrTrie.prototype.lookup = function(value) {
      var c, node, _i, _len, _ref;
      node = this.root;
      _ref = FrTrie.normalize(value).replace(spaces, '');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        c = _ref[_i];
        if (!node[c]) {
          return empty;
        }
        node = node[c];
      }
      return node['$'] || empty;
    };

    FrTrie.prototype.index = function(id, word) {
      var c, node, _i, _len;
      node = this.root;
      for (_i = 0, _len = word.length; _i < _len; _i++) {
        c = word[_i];
        if (!node[c]) {
          node[c] = {
            '$': []
          };
        }
        if (node[c]['$'].indexOf(id) === -1) {
          node[c]['$'].push(id);
        }
        node = node[c];
      }
    };

    FrTrie.prototype["delete"] = function(id, word) {
      var c, index, node, _i, _len;
      node = this.root;
      for (_i = 0, _len = word.length; _i < _len; _i++) {
        c = word[_i];
        if (!node[c]) {
          return;
        }
        index = node[c]['$'].indexOf(id);
        if (index !== -1) {
          node[c]['$'].splice(index, 1);
        }
        if (node[c]['$'].length === 0) {
          delete node[c];
          return;
        }
        node = node[c];
      }
    };

    FrTrie.normalize = function(text) {
      return text.replace(normalization_pattern, '').toLowerCase();
    };

    return FrTrie;

  })();

  module.exports = FrTrie;

}).call(this);
